### ISSUE TITLE
Login route implementation

### ISSUE THREAD

**Issue by Oriol-Vilalta** [jordigarciaventura/wellsphere#100]
Iteration: Iteration 5
Projects: wellsphere - Scrum

## Description
Implement the login route for the application. Implement the ability to log in using email, GitHub, and Google. This involves integrating OAuth for GitHub and Google login options.

## Tasks
-   [x] Create the login route.
-   [x] Create the fields to login with email.
-   [x] Create "GitHub login" button.
-   [x] Create "Google login" button.
-   [x] Add a button that references to the "Sign up" page.

## Acceptance Criteria
- The login page should match the rest of the application design.
- Warn the user if the login was un successful.
- OAuth login should be functional for GitHub.

## Additonal Information
The Google login and the email login aren't implemented yet.
