### ISSUE TITLE
Chat route implementation

### ISSUE THREAD

**Issue by Oriol-Vilalta** [jordigarciaventura/wellsphere#101]
## Description

Implement the chat route to allow users to communicate with the chatbot.

## Tasks

-   [x] Add an input text.
-   [x] Display previous messages.
-   [x] Save the messages sent and received to the database.

## Acceptance Criteria

-   The design should match the Figma design.
-   The chat messages should be saved in the database.
-   The chat should update in real-time without refreshing the page.

## Additional Information

The design should be based on your design on Figma. For the chat development there is a library that Jordi used on the previous sprint, if you need help ask me or him.
