### ISSUE TITLE
Settings route implementation

### ISSUE THREAD

**Issue by Oriol-Vilalta** [jordigarciaventura/wellsphere#102]
## Description

Implement the settings route to allow users to configure their preferences within the app.

## Tasks

-   [x] Create the settings route.
-   [x] Add a "Language picker" button.
-   [x] Add a "Theme picker" button.
-   [x] Add a "Disable notifications" button

## Acceptance Criteria

-   The design should match the Figma design.
-   The settings should update in real-time.

## Additional Information

Most of the functions that have to be in this page are already implemented (like the language picker and the theme picker).
