### ISSUE TITLE
Home route implementation

### ISSUE THREAD

**Issue by Oriol-Vilalta** [jordigarciaventura/wellsphere#103]
## Description

Implement the home route to serve as the main landing page for users when they open the app. This page should provide a slight view of some important features of the application, like that day's tasks and the mood through that week

## Tasks

-   [x] Create the home route.
-   [x] Add a view to show the mood tracking through the week.
-   [x] Make a scrollable view for today's tasks
-   [x] Add a brief motivational message for the user to see.

## Acceptance Criteria

-   The design should match the Figma design.
-   The home route should be responsive and work well on both mobile and desktop.

## Additional Information

Ensure the home route provides a good user experience and is visually appealing. This page is the first that the users will see, if there's any idea of a new feature that would be interesting to the user, we can talk about it. But in this page should be as simple as possible, for the user's experience.
