### ISSUE TITLE
Credential Authentication

### ISSUE THREAD

**Issue by Oriol-Vilalta** [jordigarciaventura/wellsphere#109]
## Description

Implement a new feature for credential authentication to enhance security. This feature should include:

## Tasks

-   [ ] Redesign the page.
-   [ ] Create the CredentialsProvider
-   [ ] Password encryption
-   [ ] Token-based authentication
-   [ ] Error handling for invalid credentials

## Acceptance Criteria

- The user should be able to login with the username and the password.
- While signing up the user must repeat the password.
- The password should be encrypted in the database

## Additional information

Out of the three methods of authentication that we want to add, this should be the more time consuming. Since it will be easier to create an account using the username rather than the email, this should be worth the time.
