### ISSUE TITLE
Insights Route Page

### ISSUE THREAD

**Issue by raphael-santosz** [jordigarciaventura/wellsphere#129]
## Description

Implement the Insights page to display all user tracking and statistics.

## Tasks

-   [ ] Retrieve data from the questionnaire database.
-   [ ] Match questionnaire goals with completed/incomplete tasks to calculate progress.
-   [x] Display all relevant graphs as designed in Figma.

## Acceptance Criteria

- Calculations must be performed first to ensure data accuracy.
- The design must be clean and visually appealing.

## Additional information

If it’s not possible to generate the graphs due to insufficient data, such as missing questionnaire or user task information, prioritize addressing these needs first. We have to delivery the funcionability with real data.
