### ISSUE TITLE
Handover meeting 11/22

### ISSUE THREAD

**Issue by raphael-santosz** [jordigarciaventura/wellsphere#132]
## Description

Handover meeting where Oriol was passing his activities from previous sprint to Raphael to guide him as new Projeto Owner.

## Tasks

-   [ ] Show the application overview.
-   [ ] Guide through the responsabilities of PO.
-   [ ] Create the new cronogram of the sprint

## Acceptance Criteria

- All the assignes be present.

## Additional information

Were discussed all the topics related to management and distribution of the tasks, also important to highlight that the handover was done with Oriol showing his methods to do each PO task perfectly.
