### ISSUE TITLE
DOC - Plannification for Current Sprint

### ISSUE THREAD

**Issue by raphael-santosz** [jordigarciaventura/wellsphere#145]
## Description

Create the planning section of the document that will be delivered to the clients (teachers).

## Tasks

-   [ ] Design a template to structure the document before adding real data.
-   [ ] Include the Sprint backlog tasks.
-   [ ] Add estimated dedication time for each task.
-   [ ] Include an indicator of evolution between sprints. Specify any changes compared to the previous sprint.

## Acceptance Criteria

- The document must include all information required by the teachers.

## Additional information

Starting with a template for each section will save time when the real data is ready to be added. This approach ensures efficiency and consistency.
