### ISSUE TITLE
Create the Agenda for the Weekly Meeting 1/12

### ISSUE THREAD

**Issue by raphael-santosz** [jordigarciaventura/wellsphere#155]
## Description

Basicly, to create the order of the day for the meeting. The topics that should be discussed and the expected time of the reunion.

## Tasks

-   [x] Create the order of the day header.
-   [x] Create the discussion topics .
-   [x] Send the document to our WhattsApp group.

## Acceptance Criteria

- The document must have the place of the reunion, the date and the hour.
