### ISSUE TITLE
Sprint 2 - PDF

### ISSUE THREAD

**Issue by jordigarciaventura** [jordigarciaventura/wellsphere#59]
## Description

Create a technical document (PDF) to show the state of the project at the end of Sprint 2.

## Tasks

-   [ ] Planification for current Sprint
    -   [ ] Sprint backlog tasks.
    -   [ ] Dedication time to each one (an estimation).
    -   [ ] Indicator related to evolution between Sprints. Concretely, if there is some change it should be specified.
-   [ ] Requirements - Product backlog – Sprint backlog
    -   [ ] The current list of requirements should be well defined and well explained for any participant.
    -   [ ] Indicator related to evolution between Sprints. Concretely, if there is some change, for example new requirements or modification inside an existing one, it should be specified.
-   [ ] Main use cases
    -   [ ] List.
    -   [ ] Reason to be essential.
    -   [ ] Indicator related to evolution between Sprints. Concretely, if there is some change it should be specified.
-   [ ] General architecture
    -   [ ] Definition (relational diagram, image, etc.).
    -   [ ] Explanation.
    -   [ ] Decisions taken.
    -   [ ] Indicator related to evolution between Sprints. Concretely, if there is some change it should be specified.
-   [ ] Database model
    -   [ ] Definition (for example: relational diagram).
    -   [ ] Explanation.
    -   [ ] Decisions taken.
    -   [ ] Indicator related to evolution between Sprints. Concretely, if there is some change, for example new requirements or modification inside an existing one, it should be specified.
-   [ ] Main screens design
    -   [ ] Relations.
    -   [ ] Decisions taken.
    -   [ ] Improvements to existing screens.
    -   [ ] Indicator related to evolution between Sprints. Concretely, if there is some change it should be specified.
-   [ ] Project Cost Management
    -   [ ] Are there any resources you need to add at this stage (Sprint 2)? Why?
    -   [ ] Update the project time period, if changed it and needed. Justify it.
    -   [ ] Update all project resources and costs at this Sprint 2.
    -   [ ] Draw all tasks, subtasks, and resources in a Gantt chart. How many tasks/goals are achieved at this Sprint 2? Justify it.
    -   [ ] Compare the evolution Sprint 1 vs Sprint 2 related with different resources, costs and time period. Explain it.
    -   [ ] Explain and justify which kind of revenue/income you expect for this project.

## Acceptance Criteria

The document should be well structured and easy to read. It should contain all the information requested in the tasks. Don't overcomplicate the document, keep it simple and clear. Go straight to the point. It shouldn't contain any spelling or grammar mistakes. It's preferrable to use images and diagrams to explain the concepts. Don't just attach images, explain them.
The document should include a front page with the project name, university, subject, teachers, the sprint number, the date, and the names of the participants.
A table of contents is required. The images and diagrams should be referenced in the text and include a caption.

## Implementation Details

Use google docs so everyone can collaborate (share the link). Reuse the front page created on Overleaf for the first sprint.
