### ISSUE TITLE
Get AI free API access

### ISSUE THREAD

**Issue by jordigarciaventura** [jordigarciaventura/wellsphere#61]
## Description

Get access to a free AI API to use in the app.

## Tasks

-   [ ] Access to an LLM API.
-   [ ] Access to an Embedding API.
-   [ ] Access to a Speech to text API.

## Acceptance Criteria

-   The APIs should be free.
-   The free tier should be enough for the app.

## Implementation Details

Look for the APIs in the following providers: OpenAI, Google, Azure, Amazon.

Useful links:

-   https://openai.com/form/researcher-access-program/
-   https://openai.com/contact-sales/
-   https://cloud.google.com/free/
