### ISSUE TITLE
Tasks route implementation

### ISSUE THREAD

**Issue by jordigarciaventura** [jordigarciaventura/wellsphere#62]
## Description

Implement the tasks route.

## Tasks

-   [ ] Create the tasks route.
-   [ ] Add the tasks to the database.
-   [ ] Show the tasks in the route.
-   [ ] Mark tasks as done.
-   [ ] Delete tasks.
-   [ ] Go to task route when clicking on a task.

## Additional Information

-   When running `npm run build` the app should compile without errors.
-   The design should match the Figma design.
-   The tasks should be saved in the database.

## Implementation Details

Try to use tailwind to style the components.
