### ISSUE TITLE
Sprint 2 - Presentation

### ISSUE THREAD

**Issue by jordigarciaventura** [jordigarciaventura/wellsphere#64]
## Description

Create a presentation (slides) to show the state of the project at the end of Sprint 2.

## Tasks

-   [ ] Create the template
-   [ ] Specify the content
-   [ ] Create the slides
-   [ ] Assign the slides to each participant

## Acceptance Criteria

-   The template should be aligned with the technical document.
-   Avoid adding text to the slides, use bullet points and images.
-   The slides should be well structured and easy to follow.
-   The slides should be visually appealing (use light theme and 16:9 format).
-   Add the logo of the company on each slide (ensure it can be easily modified).
-   The slides should include a front page with the project name, university, subject, teachers, the sprint number, the date, and the names of the participants.
-   The slides should include a table of contents.
-   The content should be interesting and engaging, don't add boring slides.

## Additional Information

Use Google Slides so everyone can collaborate (share the link). Make a big effort on the template so we can use the same for the next sprint and the final presentation.
