### ISSUE TITLE
Insights route redesign

### ISSUE THREAD

**Issue by jordigarciaventura** [jordigarciaventura/wellsphere#68]
## Description

Redesign the insights route to match the new design of the app, improve it and make the the desktop version too.

## Tasks

-   [ ] Specify the data to show.
-   [ ] Specify how to show the data.
-   [ ] Create the new design for desktop.

## Acceptance Criteria

-   The charts should be easy to read and understand.
-   The data should be meaningful and useful for the user.
-   The design should match the rest of the app.
-   The mobile and desktop versions should be consistent.
-   Use the colors of the dimensions.

## Additional Information

Create a section in Figma for this route and add at least two frames, one for the design for mobile and other for desktop. You can use screenshots from some JS chart library to show the data. Because making the charts is hard, maybe it's easier to make them in the app first and then take screenshots and place them in the Figma design.
