### ISSUE TITLE
Tasks route redesign

### ISSUE THREAD

**Issue by jordigarciaventura** [jordigarciaventura/wellsphere#69]
## Description

Improve the current tasks route design and add the desktop version.

## Tasks

-   [x] Show dimensions for each task.
-   [x] Add checkboxes to mark tasks as done.
-   [ ] Create the new design for desktop.
-   [x] Show habits in a different section.

## Acceptance Criteria

-   The design should match the rest of the app.
-   The mobile and desktop versions should be consistent.

## Additional Information

Create a section in Figma for this route and add at least two frames, one for the design for mobile and other for desktop.
