### ISSUE TITLE
New task route redesign

### ISSUE THREAD

**Issue by jordigarciaventura** [jordigarciaventura/wellsphere#70]
## Description

Improve the current new task route design and add the desktop version.

## Tasks

-   [x] Use the colors of the dimensions for the category selector.
-   [x] Merge start and end date in the date field (specifying the start/end time can be optional).
-   [x] Add reminder button to configure notifications.
-   [x] Add recurrence button (see Google Calendar for inspiration).
-   [x] Create the new design for desktop.

## Acceptance Criteria

-   The design should match the rest of the app.
-   The mobile and desktop versions should be consistent.

## Additional Information

Create a section in Figma for this route and add at least two frames, one for the design for mobile and other for desktop.
