### ISSUE TITLE
Task route design

### ISSUE THREAD

**Issue by jordigarciaventura** [jordigarciaventura/wellsphere#71]
## Description

Create a design for the task route, for mobile and desktop.

## Tasks

-   [x] Show the task details.
-   [x] Show an edit button.
-   [x] Show a delete button.
-   [x] Show the dimension of the task.
-   [x] Show the date of the task.
-   [x] Show the recurrence of the task.
-   [x] Show the reminders of the task.

## Acceptance Criteria

-   The design should match the rest of the app.
-   The mobile and desktop versions should be consistent.

## Additional Information

Create a section in Figma for this route and add at least two frames, one for the design for mobile and other for desktop.
