### ISSUE TITLE
Journal route redesign

### ISSUE THREAD

**Issue by jordigarciaventura** [jordigarciaventura/wellsphere#72]
## Description

Improve the current journal route design and add the desktop version.

## Tasks

-   [ ] Move the mood selector below the week calendar.
-   [ ] Change mood emojis (see Daylio for inspiration).
-   [ ] Remove the `Write` button because the journal should be always editable.
-   [ ] Add a button for answering a questionnaire.
-   [ ] Show the answers of the questionnaire in the journal.
-   [ ] Create the new design for desktop.

## Acceptance Criteria

-   The design should match the rest of the app.
-   The mobile and desktop versions should be consistent.

## Additional Information

Create a section in Figma for this route and add at least two frames, one for the design for mobile and other for desktop.
