### ISSUE TITLE
Login route redesign

### ISSUE THREAD

**Issue by jordigarciaventura** [jordigarciaventura/wellsphere#73]
## Description

Improve the current login route design and add the desktop version.

## Tasks

-   [ ] Add a button for login with Google.
-   [ ] Add a button for login with GitHub.
-   [ ] Create the new design for desktop.

## Acceptance Criteria

-   The design should match the rest of the app.
-   The mobile and desktop versions should be consistent.

## Additional Information

Create a section in Figma for this route and add at least two frames, one for the design for mobile and other for desktop.
