### ISSUE TITLE
Improve PWA manifest

### ISSUE THREAD

**Issue by jordigarciaventura** [jordigarciaventura/wellsphere#75]
## Description

Improve the PWA manifest to make the installation process more user-friendly.

## Tasks

-   [x] Add screenshots from the Figma design.
-   [x] Add some description when installing the app.
-   [x] Modify the color of the top bar to match the main primary color of the app.
-   [ ] Add multiple languages.

## Acceptance Criteria

-   Get a good score on Lighthouse.
-   Get a good score on PWA Builder.
-   The icon should look good on every device.

## Additional Information

Ensure you know each of the features that you write in the manifest.ts file. Try to install this app: [squoosh](https://squoosh.app/) as an example.

You can find information about the translations in the [w3 specification](https://www.w3.org/TR/localizable-manifests/#example-5).

Look these resources:

-   https://github.com/elegantapp/pwa-asset-generator
-   https://www.pwabuilder.com/
-   https://maskable.app/
