### ISSUE TITLE
Settings route design

### ISSUE THREAD

**Issue by Oriol-Vilalta** [jordigarciaventura/wellsphere#85]
## Description

Design a new route for the questionnaire feature that aligns with the updated app design. Ensure the route is optimized for both mobile and desktop versions.

## Tasks

-   [x] Add a "Change Theme" option.
-   [x] Add a "Change Language" option.
-   [x] Add a "Disable/Enable Notifications" option.
-   [x] Add an "Upgrade to Pro" option.

## Acceptance Criteria

-   The design should match the rest of the app.
-   The mobile and desktop versions should be consistent.
-   The "Upgrade to Pro" option should be different in order to attract the users attention.

## Additional Information

Create a section in Figma for this route and add at least two frames, one for the design for mobile and other for desktop.

---
