### ISSUE TITLE

Tasks route implementation

### ISSUE THREAD

**Issue by Oriol-Vilalta** [jordigarciaventura/wellsphere#90]
Iteration: Iteration 5
Projects: wellsphere - Scrum

## Description

Implement the tasks page route that allows users to view tasks. The implementation should be consistent with the overall app design and provide a seamless user experience on both mobile and desktop devices. 

## Tasks

-   [x] Create the data-access file to interact with the database. Deletion and Viewing (one task).
-   [x] Create a new page for the tasks route.
-   [x] Design the page using React.
-   [x] Create the day selection bar.
-   [x] Create the "Add Task" button.
-   [ ] Create a menu that allows to edit and delete tasks.
-   [x] Create the tasks list.

## Acceptance Criteria

-   The tasks route should match the rest of the app design. 
-   The interface should be user friendly.
-   The tasks page should match the style of the app.
-   The tasks colour should match each dimension assigned colour.
-   The task list should display the task for that specific day.
-   The task list should show the actual day as default.

## Additional Information

Refer to the design specifications in Figma for the tasks route. At the moment, the database cannot hold some of the features that task should be doing like selecting weekdays and a start or ending time.
If you encounter any other problem relative to the design or the database we can talk about it.
