### ISSUE TITLE

Task creation and modification implementation

### ISSUE THREAD

**Issue by Oriol-Vilalta** [jordigarciaventura/wellsphere#91]
Iteration: Iteration 5
Projects: wellsphere - Scrum

## Description

Implement a page that allows the user to create a task or modify an exisiting one.

## Tasks

-   [ ] Create the data-access file to interact with the database. Creation, Modification and Viewing (one task).
-   [ ] Create a new page for the "New/Modify tasks".
-   [ ] Design the page using React.
-   [ ] Create the a day selection bar (week days) as toggle buttons.
-   [ ] Create a date selection button.
-   [ ] Create a time picker field (starting and ending time).
-   [ ] Create a frecuency button.
-   [ ] Create the text sections (Title, Description).
-   [ ] Create the dimension picker.

## Acceptance Criteria

-   If the task is modified, the default values of the task should be displayed.
-   All the fields should be modifiable.
-   The "Commit changes" should display a different prompt depending on the action. Ex: Creation ("Create task"), Update ("Apply Changes", "Create App").

## Additional Information

As the prievious issue, at the moment, the database cannot hold the actions required to save the tasks with all the fields.
