### ISSUE TITLE

Create "Data Access" to the tasks pages.

### ISSUE THREAD

**Issue by Oriol-Vilalta** [jordigarciaventura/wellsphere#92]
Iteration: Iteration 5
Projects: wellsphere - Scrum

## Description

Design a strategy to save tasks on the database with the following new features:

## Tasks

-   [x] Create an strategy to save the missing field. (Date, starting and ending time, frequency, week days).
-   [x] Test changes to prevent incoherences.
-   [x] Create the tasks data access file.
-   [x] Update the schema design.

## Acceptance Criteria

-   The database should be functional and be able to do the CRUD functions without incoherences. 

## Additiona Information

Thanks to Drizzle there will be no problems with the new changes, but this will be the first migration since the createion of the database. Run locally there will be no problem since we are not saving the database, but maybe there will be errors modifing the database on the deployment.
