### ISSUE TITLE
Journal route implementation

### ISSUE THREAD

**Issue by Oriol-Vilalta** [jordigarciaventura/wellsphere#98]
Iteration: Iteration 5
Projects: wellsphere - Scrum

## Description

Design the journal route implementation. The journal page is the one that allows the user to write his thoughts each day. Also, when filling the day's entry, there will be a mood picker option to let the user save how he felt during the day.

Once the entries are submited, the user will not be able to modify them. Additionaly the previous entries won't be updatable either. With one exception: if the previous day the user didn't create the entry, he will have the option to create that days entry before being able to create todays.

## Tasks

-   [ ] Create a button for the questionarie button.
-   [ ] Create a day picker.
-   [ ] Create a big field to save the entry.
-   [ ] Create the mood picker.
-   [ ] Create a publish button, visible only when the user can create a new entry.

## Acceptance Criteria

- The page should match the app's design.
- The previous day entries will be read-only, including the mood picker.
- The page should show the actual day as default, with the journal entry and the day picker set to today.

## Additional Information

For the journal, you can take inspiration from the Figma but the "Publish button" is missing.
